guests/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.guest_list, name='guest_list'),
    path('new', views.guest_create, name='guest_create'),
    path('view/<int:pk>', views.guest_read, name='guest_read'),
    path('edit/<int:pk>', views.guest_update, name='guest_update'),
    path('delete/<int:pk>', views.guest_delete, name='guest_delete'),
]

wedding/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from guests import views as guest_views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('guests/', include('guests.urls')),
    path('payments/', include('payments.urls')),
    path('logout/', views.guest_logout, name='guest_logout'),
    path('rsvp/', guest_views.rsvp, name='rsvp'),
    path('onsite_cost/', guest_views.onsite_cost, name='onsite_cost'),
    path('<guest_username>/', views.guest_login, name='guest_login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guests/models.py
from django.db import models
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField
from datetime import date
from decimal import Decimal


INVITED_THRESHOLD = Decimal('0.40')
AGE_THRESHOLD = 5


class Activity(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Activities'


class RSVP(models.Model):
    def __str__(self):
        leader = self.guests.first()
        if leader and str(leader):
            # Return the name of the leader of the party
            return str(leader)
        # If there is no named guest, name it by the date and time
        d = self.created
        ampm = 'pm' if d.hour >= 12 else 'am'
        return f'{d:%b} {d.day}, {d.hour}:{d:%M} {ampm}'

    def party_size(self):
        return len(self.guests.all())

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    attending = models.BooleanField()
    attending_kuwait = models.BooleanField(default=False)
    nights_onsite = models.PositiveSmallIntegerField(blank=True, default=0)
    activities = models.ManyToManyField(Activity, related_name='groups')
    payment = models.OneToOneField(
        'payments.Payment', blank=True, null=True, on_delete=models.SET_NULL)
    message = models.TextField(blank=True, default='')

    class Meta:
        verbose_name = 'RSVP'


class GuestQuerySet(models.QuerySet):
    def leads(self):
        return self.filter(lead_partner=None, parent=None)

    def invited(self):
        return self.filter(percentile__gte=INVITED_THRESHOLD)


class Guest(models.Model):
    def __str__(self):
        return f'{self.first_name} {self.last_name}'.strip()

    def unnamed(self):
        # Returns True if guest has no name, False if they do
        return not bool(str(self))

    def is_lead(self):
        return not self.lead_partner and not self.parent
    is_lead.boolean = True
    is_lead.short_description = 'Group Lead'

    def invited(self):
        return self.percentile >= INVITED_THRESHOLD
    invited.boolean = True

    def age(self):
        if self.birthday:
            delta = date.today() - self.birthday
            years = int(delta.days / 365.25)
            return years
        else:
            return None

    def adult(self):
        return self.age() is None or self.age() >= AGE_THRESHOLD
    adult.boolean = True

    def party(self):
        party = []
        if self.lead_partner:
            # This person has a lead partner, so make them first then self
            party.append(self.lead_partner)
            party.append(self)
        elif self.parent:
            # This person has a parent, so make them first
            party.append(self.parent)
        else:
            # This person has no senior, so make self first
            party.append(self)
            # Add partner(s) if present
            for partner in self.partners.all().order_by('first_name'):
                party.append(partner)
        # Add all the children to the party, ordered by age then name
        for child in party[0].children.all().order_by(
                'birthday', 'first_name'):
            party.append(child)
        return [guest for guest in party if guest.invited()]

    def address(self):
        if self.country == 'US':
            lines = []
            lines.append(self.thoroughfare)
            if self.premise:
                lines.append(self.premise)
            line = (f'{self.locality}, {self.administrative_area} ')
            line += self.postal_code
            lines.append(line)
            return lines
        return None

    def party_line(self, max_line_length=28):
        party = len(self.party())

        if party == 1:
            return str(self)
        elif party == 2:
            plus_one = self.party()[1]
            if plus_one.unnamed():
                line = f'{self} & Guest'
                if len(line) > max_line_length:
                    line = f'{self.first_name} & Guest'
                return line
            elif self.last_name == plus_one.last_name:
                first_names = f'{self.first_name} & {plus_one.first_name}'
                line = f'{first_names} {self.last_name}'
                if len(line) > max_line_length:
                    line = first_names
                return line
            else:
                line = f'{self} & {plus_one}'
                if len(line) > max_line_length:
                    line = f'{self} & {plus_one.first_name}'
                if len(line) > max_line_length:
                    line = f'{self.first_name} & {plus_one.first_name}'
                if len(line) > max_line_length:
                    line = f'{self.first_name} & Guest'
                return line
        else:
            line = f'{self.first_name}, '
            plus_one = self.party()[1]
            line += 'Guest' if plus_one.unnamed() else plus_one.first_name
            line += ' & Family'
            if len(line) > max_line_length:
                line = f'{self.first_name} & Family'
            return line

    username = models.SlugField(blank=True, null=True)
    phone = PhoneNumberField(blank=True)
    email = models.EmailField(blank=True, max_length=200)
    lead_partner = models.ForeignKey(
        'self',
        blank=True,
        related_name='partners',
        null=True,
        on_delete=models.SET_NULL)
    parent = models.ForeignKey(
        'self',
        blank=True,
        related_name='children',
        null=True,
        on_delete=models.SET_NULL)
    birthday = models.DateField(blank=True, null=True)
    percentile = models.DecimalField(
        default=0,
        max_digits=2,
        decimal_places=2)
    likelihood = models.DecimalField(
        default=0,
        max_digits=2,
        decimal_places=2)
    rsvp = models.ForeignKey(
        RSVP, blank=True, null=True, related_name='guests',
        on_delete=models.SET_NULL)
    family = models.PositiveSmallIntegerField(
        default=3,
        choices=(
            (1, 'Bride'),
            (2, 'Groom'),
            (3, 'Friend'),
        ))
    language = models.CharField(
        default='en',
        max_length=2,
        choices=(
            ('en', 'English'),
            ('es', 'Spanish'),
            ('ar', 'Arabic'),
        ))
    first_name = models.CharField(blank=True, max_length=40)
    last_name = models.CharField(blank=True, max_length=40)
    invite_printed = models.BooleanField(default=False)
    kuwait_invite = models.BooleanField(default=False)
    country = CountryField(blank=True)
    administrative_area = models.CharField(
        'state',
        blank=True,
        max_length=60)
    sub_administrative_area = models.CharField(
        'county',
        blank=True,
        max_length=60)
    locality = models.CharField(
        'city',
        blank=True,
        max_length=60)
    dependent_locality = models.CharField(
        'neighborhood',
        blank=True,
        max_length=60)
    postal_code = models.CharField(blank=True, max_length=20)
    thoroughfare = models.CharField(
        'street address',
        blank=True,
        max_length=60)
    premise = models.CharField(
        'apartment/box',
        blank=True,
        max_length=60)
    sub_premise = models.CharField(
        'room',
        blank=True,
        max_length=60)
    notes = models.TextField(blank=True)

    # Model managers, for filtering queries
    objects = GuestQuerySet.as_manager()

guests/views.py
from django.http import JsonResponse, HttpResponseRedirect  # noqa
from django.views.decorators.http import require_POST
from wedding.local_settings import STRIPE_SECRET_KEY
import stripe
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Guest
from .forms import GuestForm, WebRSVPForm
from payments.models import Payer, PaymentCategory, Payment
import json
from pprint import pprint  # noqa

stripe.api_key = STRIPE_SECRET_KEY


@login_required
def guest_list(request, template_name='guests/list.html'):
    guests = Guest.objects.all()
    data = {'guests': guests}
    return render(request, template_name, data)


@login_required
def guest_create(request, template_name='guests/form.html'):
    form = GuestForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('guest_list')
    data = {'form': form}
    return render(request, template_name, data)


@login_required
def guest_read(request, pk, template_name='guests/read.html'):
    guest = get_object_or_404(Guest, pk=pk)
    data = {'guest': guest}
    return render(request, template_name, data)


@login_required
def guest_update(request, pk, template_name='guests/form.html'):
    guest = get_object_or_404(Guest, pk=pk)
    form = GuestForm(request.POST or None, instance=guest)
    if form.is_valid():
        form.save()
        return redirect('guest_list')
    data = {'form': form}
    return render(request, template_name, data)


@login_required
def guest_delete(request, pk, template_name='guests/delete.html'):
    guest = get_object_or_404(Guest, pk=pk)
    if request.method == 'POST':
        guest.delete()
        return redirect('guest_list')
    data = {'guest': guest}
    return render(request, template_name, data)


def lodging_cost(guest_list, nights):
    try:
        guest_list = [Guest.objects.get(pk=g) for g in guest_list]
    except TypeError:
        # The guest list was already guest objects, not IDs
        pass
    guests = [g for g in guest_list if g.age() is None or g.age() >= 5]
    num_guests = len(guests)
    if nights == 1:
        return 90 * num_guests
    elif nights == 2:
        return 170 * num_guests
    else:
        return 0


@require_POST
def onsite_cost(request):
    data = json.loads(next(iter(request.POST)))
    cost = lodging_cost(data['party'], data['nights'])
    return JsonResponse({'cost': cost})


@require_POST
def rsvp(request):
    response = {'errors': {}}
    form = WebRSVPForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data

        for key, value in request.POST.items():
            words = key.split('_')
            if words[0] == 'unnamed':
                guest = Guest.objects.get(pk=int(words[-1]))
                if words[1] == 'first':
                    guest.first_name = value
                elif words[1] == 'last':
                    guest.last_name = value
                guest.save()

        guest = Guest.objects.get(id=cd['guest_id'])
        payment = None
        if cd['attending'] and cd['nights_onsite'] > 0:
            # The guest(s) will be staying onsite, so we need payment
            amount = lodging_cost(cd['guests'], cd['nights_onsite'])
            try:
                stripe_kwargs = {
                    'amount': int(amount * 100),  # Convert dollars to cents
                    'currency': 'usd',
                    'source': cd['stripe_token'],
                    'description': "Lodging for Tony & Haya's Wedding"}
                if guest.email:
                    stripe_kwargs['receipt_email'] = guest.email
                charge = stripe.Charge.create(**stripe_kwargs)
                payment = Payment(
                    amount=amount,
                    payer=Payer.objects.get_or_create(guest=guest)[0],
                    category=PaymentCategory.objects.get(name='Lodging'),
                    stripe_id=charge.id)
                payment.save()
            except stripe.error.CardError as card_error:
                # There was an error processing the credit card
                card_error = str(card_error)
                if 'Request req' in card_error:
                    card_error = card_error.split(':', 1)[1].strip()
                response['errors']['rsvp_cc'] = [card_error]
        if not response['errors']:
            rsvp = form.save()
            if payment:
                rsvp.payment = payment
                rsvp.save()
    else:
        # The form is invalid
        response['errors'] = form.errors

    return JsonResponse(response)

guests/templates/guests/delete.html
{% extends 'wedding/base.html' %}

{% block content %}
<h1>Delete Guest</h1>

<form method="post">
  {% csrf_token %}
  Are you sure you want to delete "{{ guest }}"?
  <input type="submit" value="Submit" />
</form>
{% endblock %}

guests/templates/guests/form.html
{% extends 'wedding/base.html' %}

{% block content %}
<h1>Guest Edit</h1>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

guests/templates/guests/list.html
{% extends 'wedding/base.html' %}

{% block content %}
<h1>Guest List</h1>

<table id="guest_list" class="display" style="width:100%">
<thead>
  <tr>
  <th>First Name</th>
  <th>Last Name</th>
  <th>Percentile</th>
  <th>Likelihood</th>
  <th>Family</th>
  <th>Email</th>
  <th>Phone</th>
  <th>Lead Partner</th>
  <th>Parent</th>
  <th>Age</th>
  <th>Username</th>
  <th>Language</th>
  <th>Country</th>
  <th>State</th>
  <th>City</th>
  <th>Postal Code</th>
  <th>Street Address</th>
  <th>Apartment/Box</th>
  <th>View</th>
  <th>Edit</th>
  <th>Delete</th>
  </tr>
</thead>
<tbody>
  {% for guest in guests %}
  <tr>
  <td>{{ guest.first_name }}</td>
  <td>{{ guest.last_name }}</td>
  <td>{{ guest.percentile }}</td>
  <td>{{ guest.likelihood }}</td>
  <td>{{ guest.get_family_display }}</td>
  <td>{{ guest.email }}</td>
  <td>{{ guest.phone }}</td>
  <td>{{ guest.lead_partner }}</td>
  <td>{{ guest.parent }}</td>
  <td>{{ guest.age }}</td>
  <td>{{ guest.username }}</td>
  <td>{{ guest.get_language_display }}</td>
  <td>{{ guest.country }}</td>
  <td>{{ guest.administrative_area }}</td>
  <td>{{ guest.locality }}</td>
  <td>{{ guest.postal_code }}</td>
  <td>{{ guest.thoroughfare }}</td>
  <td>{{ guest.premise }}</td>
  <td><a href="{% url 'guest_read' guest.id %}">View</a></td>
  <td><a href="{% url 'guest_update' guest.id %}">Edit</a></td>
  <td><a href="{% url 'guest_delete' guest.id %}">Delete</a></td>
  </tr>
  {% endfor %}
</tbody>
</table>

<a href="{% url 'guest_create' %}">New</a>
{% endblock %}

guests/templates/guests/read.html
{% extends 'wedding/base.html' %}

{% block content %}
<h1>Guest Details</h1>

<table>
  <tr>
    <td>Full Name</td>
    <td>{{ guest.full_name }}</td>
  </tr>
  <tr>
    <td>First Name</td>
    <td>{{ guest.first_name }}</td>
  </tr>
  <tr>
    <td>Last Name</td>
    <td>{{ guest.last_name }}</td>
  </tr>
  <tr>
    <td>Percentile</td>
    <td>{{ guest.percentile }}</td>
  </tr>
  <tr>
    <td>Likelihood</td>
    <td>{{ guest.likelihood }}</td>
  </tr>
  <tr>
    <td>Family</td>
    <td>{{ guest.family }}</tr>
  </tr>
  <tr>
    <td>Email</td>
    <td>{{ guest.email }}</td>
  </tr>
  <tr>
    <td>Phone</td>
    <td>{{ guest.phone }}</td>
  </tr>
  <tr>
    <td>Lead Partner</td>
    <td>{{ guest.lead_partner }}</td>
  </tr>
  <tr>
    <td>Parent</td>
    <td>{{ guest.parent }}</td>
  </tr>
  <tr>
    <td>Age</td>
    <td>{{ guest.age }}</td>
  </tr>
  <tr>
    <td>Username</td>
    <td>{{ guest.username }}</td>
  </tr>
  <tr>
    <td>Language</td>
    <td>{{ guest.language }}</td>
  </tr>
  <tr>
    <td>Country</td>
    <td>{{ guest.country }}</td>
  </tr>
  <tr>
    <td>State</td>
    <td>{{ guest.administrative_area }}</td>
  <tr>
    <td>City</td>
    <td>{{ guest.locality }}</td>
  </tr>
  <tr>
    <td>Postal Code</td>
    <td>{{ guest.postal_code }}</td>
  </tr>
  <tr>
    <td>Street</td>
    <td>{{ guest.thoroughfare }}</td>
  </tr>
  <tr>
    <td>Apartment/Box</td>
    <td>{{ guest.premise }}</td>
  </tr>
  <tr>
    <td>Notes</td>
    <td>{{ guest.notes }}</td>
  </tr>
</table>
{% endblock %}